---
- name: Playbook template for EE build
  hosts: localhost
  gather_facts: false
  collections:
    - redhat_cop.ee_utilities
  vars:
    ee_create_ansible_config: true #
    ee_list:
      - name: ee-aap-utilities
        tag: v1.0
        base_image: 'registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest'
        bindep:
          - python38-requests [platform:centos-8 platform:rhel-8]
          - python38-pyyaml [platform:centos-8 platform:rhel-8]
        python:
          - pytz  # for schedule_rrule lookup plugin
          - python-dateutil>=2.7.0  # schedule_rrule
          - awxkit  # For import and export modules
        collections:
          - name: awx.awx
          - name: redhat_cop.controller_configuration
          - name: redhat_cop.ah_configuration
        prepend:
          - RUN whoami
          - RUN cat /etc/os-release
        append:
          - RUN echo This is a post-install command!

  roles:
    - redhat_cop.ee_utilities.ee_builder